#!/usr/bin/env bash
set -euf -o pipefail

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MODULE_REGEX="^[\./]+$|.git"

function sym_link {
  ln -sf $1 $2
}

function get_modules {
  find $1 ! -path ${CWD} -type d | egrep -v "${MODULE_REGEX}"
}

function link_files { 
  FILES_TO_LINK=$(find $1 -regex '.*\.link$')
  for FILE in ${FILES_TO_LINK}
  do
    DEST="${HOME}/.$(basename ${FILE} .link)"
    echo "Linking ${FILE} to ${DEST}"
    sym_link ${FILE} ${DEST} 
  done
}

function link_modules {
  for MODULE in $(get_modules $1)
  do
    link_files "${MODULE}"
  done
}

function bootstrap_module {
  BOOTSTRAPS=$(find $1 -regex '.*\.run$')
  for BOOTSTRAP in ${BOOTSTRAPS}
  do
    echo "Running bootstrap $BOOTSTRAP"
    $BOOTSTRAP
  done
}

function bootstrap_modules {
  for MODULE in $(get_modules $1)
  do
    bootstrap_module "${MODULE}"
  done
}

link_modules "$CWD"
bootstrap_modules "$CWD"
