#!/usr/bin/env bash

. ${UTILS}/gh-release-utils.sh

if [[ -n ${MACOS} ]]; then
  brew tap homebrew/cask-fonts
  brew install --cask font-fira-code
elif [[ -n ${LINUX} ]]; then
  FONTS_DIR="${HOME}/.local/share/fonts"
  if [ ! -d "${FONTS_DIR}" ]; then
    mkdir -p "${FONTS_DIR}"
  fi

  DOWNLOAD_TMP="$(tempfile)"
  download_release tonsky/FiraCode "Fira_Code_v.*.zip" "${DOWNLOAD_TMP}"
  unzip -o -q -d "${FONTS_DIR}" "${DOWNLOAD_TMP}"
  fc-cache -f
fi
